# Generated by Django 5.0.2 on 2024-03-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('apply_promo_code', 'Peut appliquer des migrations'), ('apply_promo', 'Peut appliquer des migrations')], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
